# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_ejemplo',
                'doc_host': 'https://Palazrak.github.io',
                'git_url': 'https://github.com/Palazrak/nbdev_ejemplo',
                'lib_path': 'nbdev_ejemplo'},
  'syms': { 'nbdev_ejemplo.core': {'nbdev_ejemplo.core.foo': ('administrador.html#foo', 'nbdev_ejemplo/core.py')},
            'nbdev_ejemplo.tarea': { 'nbdev_ejemplo.tarea.Tarea': ('tarea.html#tarea', 'nbdev_ejemplo/tarea.py'),
                                     'nbdev_ejemplo.tarea.Tarea.__init__': ('tarea.html#tarea.__init__', 'nbdev_ejemplo/tarea.py'),
                                     'nbdev_ejemplo.tarea.Tarea.__str__': ('tarea.html#tarea.__str__', 'nbdev_ejemplo/tarea.py'),
                                     'nbdev_ejemplo.tarea.Tarea.tarea_completada': ( 'tarea.html#tarea.tarea_completada',
                                                                                     'nbdev_ejemplo/tarea.py')}}}
