# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_administrador.ipynb.

# %% auto 0
__all__ = ['Administrador']

# %% ../nbs/01_administrador.ipynb 3
class Administrador:
    "Crea un administrador de tareas"
    def __init__(self) -> None:
        self.lista_tareas = []
    def agrega_tarea(self, 
                 titulo:str, # Título de la tarea
                 fecha_entrega:str, # Fecha de entrega en formato dd/mm/aaaa. De no estar escrito así, marcará error
                 descripcion:str='' # Información adicional sobre la tarea
                 ) -> bool: #Regresa si la tarea se agregó exitosamente o no
        "Crea una tarea, la agrega a la lista y la ordena con base en la fecha de entrega"
        tarea = Tarea(titulo=titulo, fecha_entrega=fecha_entrega, descripcion=descripcion)
        self.lista_tareas.append(tarea)
        self.lista_tareas = sorted(self.lista_tareas, key=lambda x:datetime.strptime(x.fecha_entrega, "%d/%m/%Y"))
    def imprime_completo(self) -> str:
        "Imprime todas las tareas en la lista"
        for tarea in self.lista_tareas:
            print(tarea)
            
    def imprime_faltantes(self) -> str:
        "Regresa las tareas que no han sido completadas"
        for tarea in self.lista_tareas:
            if tarea.completado == False:
                print(tarea)
    __repr__ = imprime_completo
    def tarea_completada(self, 
                         titulo:str # Título de la tarea que se busca
                         )-> bool: # Regresa True si la tarea estaba en la lista y la marcó como completada
        "Busca una tarea por su nombre y la marca como completado"
        for tarea in self.lista_tareas:
            if tarea.titulo == titulo:
                tarea.completado = True
                return True
        return False
