# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_administrador.ipynb.

# %% auto 0
__all__ = ['Administrador']

# %% ../nbs/01_administrador.ipynb 3
class Administrador:
    "Crea un administrador de tareas"
    def __init__(self) -> None:
        self.lista_tareas = []
    def agrega_tarea(self, 
                 titulo:str, # Título de la tarea
                 fecha_entrega:str, # Fecha de entrega en formato dd/mm/aaaa. De no estar escrito así, marcará error
                 completado:bool=False, # Indica si ya se entregó o no
                 descripcion:str='' # Información adicional sobre la tarea
                 ) -> bool: #Regresa si la tarea se agregó exitosamente o no
        "Crea una tarea, la agrega a la lista y la ordena con base en la fecha de entrega"
        tarea = Tarea(titulo, fecha_entrega, completado, descripcion)
        insort(self.lista_tareas, tarea)
    def imprime(self) -> str:
        "Imprime todas las tareas en la lista"
        for tarea in self.lista_tareas:
            print(tarea)
    __repr__ = imprime
    def tarea_completada(self, 
                         titulo:str # Título de la tarea que se busca
                         ) -> bool: # Regresa True si se ejecutó exitosamente
        "Busca una tarea por su nombre y la marca como completado"
        for tarea in self.lista_tareas:
            if tarea.titulo == titulo:
                tarea.completado = True
                return True
        return False
