# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_articulo.ipynb.

# %% auto 0
__all__ = ['Articulo']

# %% ../nbs/02_articulo.ipynb 3
class Articulo:
    "Crea un artículo de supermercado con un nombre. Inicializa el 'estado' en False, para saber que no ha sido adquirido"
    def __init__(self, 
                 nombre:str, # Título del artículo
                 ) -> None:
        self.nombre = nombre
        self.estado = False
    def __str__(self) -> str:
        "Regresa la informacion completa sobre el artículo"
        return f"Artículo: {self.nombre}. Agregado al carrrito: {self.estado}"
    __repr__ = __str__ 
